services:
  - type: web
    name: wfx-trading-competition
    runtime: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: bash ./start-server.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: VITE_SUPABASE_URL
        value: https://cujdemfiikeoamryjwza.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1amRlbWZpaWtlb2Ftcnlqd3phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0OTE1OTEsImV4cCI6MjA4MjA2NzU5MX0.yfO_neHiPBBWx7AzYuk5sd4sIocv2BSvtkdzgmpDjC4
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1amRlbWZpaWtlb2Ftcnlqd3phIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NjQ5MTU5MSwiZXhwIjoyMDgyMDY3NTkxfQ.OhYhBnz05h-LmUf2-RvyjJuggSdp_HmD0siIDuoVCBk
      - key: RESEND_API_KEY
        value: re_5uzTUbXE_9DAFScadBWszUXrED2mnDE7v
      - key: FLUTTERWAVE_PUBLIC_KEY
        value: FLWPUBK_84a33abb9577491b5bc7e1ce856de21a
      - key: FLUTTERWAVE_SECRET_KEY
        value: FLWSECK_1036173a3165024b79ebf88a283d8fa7
      - key: FLUTTERWAVE_SECRET_HASH
        value: wfx-contest-showdown-competition
      - key: BINANCE_MERCHANT_ID
        value: "48947748"
      - key: BYBIT_USDT_WALLET_ADDRESS
        value: TH9F2BfgD6C7gM5Jxo8gM3EpxU42kRUJm5
      - key: EMAIL_FROM
        value: onboarding@resend.dev
      - key: ADMIN_PASSWORD
        value: Winning@708
